Fareye superset auth ver 9.0
far-eye/incubator-superset pull request #52
Opened 2021-09-14 10:22 UTC by mborkhat

Adding Addition Layer for authentication.

1.Adding a layer for dashboard access for mobi user, it uses JWT authentication mode.

2021-09-14 11:14 UTC, saurabnigam requested changes

2021-09-14 11:14 UTC, saurabnigam commented on superset/additional_authentication_layer.py
> +DEFAULT_MOBI_USER = "mobi_user"
This will also be picked from config, remove hard coding

2021-09-14 11:14 UTC, saurabnigam commented on superset/additional_authentication_layer.py
> +   #"If url contains mobi_filter, it skips Google authentication and validates the user with JWT token"
Remove google authentication comment. Instead write tries to create session if valid jwt token is found

2021-09-14 11:14 UTC, saurabnigam commented on superset/additional_authentication_layer.py
> +                    logger.exception("Token expired!", e2)
Change error message

2021-09-14 11:14 UTC, saurabnigam commented on superset/config.py
> +
remove this

2021-09-14 11:14 UTC, saurabnigam commented on superset/config.py
> +        pass
is this tested!

2021-09-14 12:19 UTC, mborkhat commented on superset/additional_authentication_layer.py
> +DEFAULT_MOBI_USER = "mobi_user"
Change done.

2021-09-14 12:20 UTC, mborkhat commented on superset/additional_authentication_layer.py
> +   #"If url contains mobi_filter, it skips Google authentication and validates the user with JWT token"
change done

2021-09-14 12:22 UTC, mborkhat commented on superset/config.py
> +
Removed the comment. as Auth_OAUTH enables google auth.

2021-09-14 12:55 UTC, mborkhat commented on superset/additional_authentication_layer.py
> +                    logger.exception("Token expired!", e2)
done

2021-09-14 13:01 UTC, mborkhat commented on superset/config.py
> +        pass
No. Testing it

2021-09-15 11:24 UTC, saurabnigam approved these changes

2021-09-15 18:17 UTC, merged